# Generated by Django 4.2.29 on 2026-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_booking_booking_type_service_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Commission percentage per service (for salary calculation)', max_digits=5),
        ),
    ]
