# Generated by Django 4.2.29 on 2026-05-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_closedday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(default='massage', help_text='Comma-separated categories', max_length=200),
        ),
    ]
