# Generated by Django 5.2.15 on 2026-07-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_staffleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleave',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, this leave has been cancelled or ended'),
        ),
    ]
