# Generated by Django 5.2.15 on 2026-08-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_staffleave_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(help_text='Select one or more services', related_name='bookings', to='website.service'),
        ),
    ]
