# Generated by Django 5.2.15 on 2026-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_booking_service_booking_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True if client verified their email OTP'),
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
