# Generated by Django 5.2.15 on 2026-08-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_booking_is_verified_booking_verification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM'), ('19:00', '7:00 PM'), ('20:00', '8:00 PM'), ('21:00', '9:00 PM'), ('22:00', '10:00 PM'), ('23:00', '11:00 PM'), ('00:00', '12:00 MN')], max_length=5),
        ),
    ]
