# Generated by Django 5.2.15 on 2026-09-10 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_contactmessage_replied_at_contactmessage_reply_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='locked_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price locked in at time of booking', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_prices_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of services and their prices at time of booking', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM'), ('19:00', '7:00 PM'), ('20:00', '8:00 PM'), ('21:00', '9:00 PM'), ('22:00', '10:00 PM')], max_length=5),
        ),
        migrations.CreateModel(
            name='ServicePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Regular/Original price', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage at this time', max_digits=5)),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date when this price became active')),
                ('effective_to', models.DateField(blank=True, help_text='Date when this price ended (null if currently active)', null=True)),
                ('notes', models.CharField(blank=True, default='', help_text='e.g. Regular Rate, Summer Promo, Price Adjustment', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='website.service')),
            ],
            options={
                'verbose_name': 'Service Price History',
                'verbose_name_plural': 'Service Price Histories',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
