# Generated by Django 5.2.15 on 2026-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_booking_locked_price_booking_service_prices_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('awaiting_verification', 'Awaiting Verification'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_verification', max_length=25),
        ),
    ]
