# Generated by Django 5.2.15 on 2026-09-19 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_add_awaiting_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='access_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Admin / Staff'), ('client', 'Client')], default='admin', max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('email_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='website.contactmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
