# Generated by Django 5.2.15 on 2026-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_contactmessage_access_token_messagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
