# Generated by Django 5.2.15 on 2026-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_contactmessage_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived bookings are hidden from main list but not deleted'),
        ),
    ]
