# Generated by Django 5.2.15 on 2026-09-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_booking_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rebooking_token',
            field=models.UUIDField(blank=True, db_index=True, help_text='One-time UUID token sent to client when booking is cancelled due to staff leave. Cleared after use.', null=True),
        ),
    ]
