"""Editable client-facing website copy and its safe defaults."""

SITE_CONTENT_FIELDS = [
    # Business identity and contact information
    {"key": "business_name", "group": "Business Information", "label": "Business name", "value": "MEDPOINT", "input_type": "text", "help_text": "Shown in the website header and footer."},
    {"key": "business_legal_name", "group": "Business Information", "label": "Full business name", "value": "MEDPOINT Massage & Spa", "input_type": "text"},
    {"key": "business_tagline", "group": "Business Information", "label": "Business tagline", "value": "Massage & Spa", "input_type": "text"},
    {"key": "meta_description", "group": "Business Information", "label": "Search description", "value": "MEDPOINT Massage and Spa - Premium massage therapy and spa wellness services. Book your relaxation today.", "input_type": "textarea", "help_text": "Used by search engines and link previews."},
    {"key": "owner_name", "group": "Business Information", "label": "Owner name", "value": "", "input_type": "text", "help_text": "Kept here for future ownership changes."},
    {"key": "manager_name", "group": "Business Information", "label": "Manager name", "value": "", "input_type": "text", "help_text": "Kept here for future management changes."},
    {"key": "address", "group": "Contact Information", "label": "Business address", "value": "Gallares Street, Tagbilaran City, Bohol, Philippines", "input_type": "textarea"},
    {"key": "phone", "group": "Contact Information", "label": "Contact number", "value": "+63 928 356 8231", "input_type": "phone"},
    {"key": "email", "group": "Contact Information", "label": "Email address", "value": "medpointmassage.spa@gmail.com", "input_type": "email"},
    {"key": "business_hours", "group": "Contact Information", "label": "Daily operating hours", "value": "10:00 AM - 12:00 MN", "input_type": "text", "help_text": "The business currently operates Monday through Sunday."},
    {"key": "facebook_url", "group": "Contact Information", "label": "Facebook page URL", "value": "https://www.facebook.com/MedpointSpa", "input_type": "url"},
    {"key": "footer_description", "group": "Footer", "label": "Footer description", "value": "Experience the harmony of body and soul. Premium wellness treatments by expert therapists.", "input_type": "textarea"},
    {"key": "copyright_text", "group": "Footer", "label": "Copyright text", "value": "© 2026 MEDPOINT Massage & Spa. All rights reserved.", "input_type": "text"},

    # Home page
    {"key": "home_hero_eyebrow", "group": "Home Page", "label": "Hero eyebrow", "value": "Welcome to MEDPOINT", "input_type": "text"},
    {"key": "home_hero_title", "group": "Home Page", "label": "Hero title", "value": "Harmony of", "input_type": "text"},
    {"key": "home_hero_title_accent", "group": "Home Page", "label": "Hero highlighted title", "value": "Body & Soul", "input_type": "text"},
    {"key": "home_hero_description", "group": "Home Page", "label": "Hero description", "value": "Discover the art of relaxation at MEDPOINT Massage & Spa. Our expert therapists deliver premium wellness treatments crafted for your complete rejuvenation.", "input_type": "textarea"},
    {"key": "home_about_label", "group": "Home Page", "label": "About section label", "value": "About Us", "input_type": "text"},
    {"key": "home_about_title", "group": "Home Page", "label": "About section title", "value": "A Sanctuary of Wellness & Beauty", "input_type": "text"},
    {"key": "home_about_description", "group": "Home Page", "label": "About section description", "value": "At MEDPOINT Massage & Spa, we believe in the healing power of touch. Our sanctuary is designed to transport you to a world of tranquility, where every treatment is crafted with care and precision.", "input_type": "textarea"},
    {"key": "home_services_title", "group": "Home Page", "label": "Services section title", "value": "Premium Spa Treatments", "input_type": "text"},
    {"key": "home_services_description", "group": "Home Page", "label": "Services section description", "value": "Indulge in our carefully curated selection of massage and spa treatments designed for your ultimate relaxation.", "input_type": "textarea"},
    {"key": "home_stat_clients_value", "group": "Home Statistics", "label": "Happy clients number", "value": "5024", "input_type": "number", "help_text": "A plus sign is displayed automatically."},
    {"key": "home_stat_clients_label", "group": "Home Statistics", "label": "Happy clients label", "value": "Happy Clients", "input_type": "text"},
    {"key": "home_stat_therapists_value", "group": "Home Statistics", "label": "Therapists number", "value": "4", "input_type": "number", "help_text": "A plus sign is displayed automatically."},
    {"key": "home_stat_therapists_label", "group": "Home Statistics", "label": "Therapists label", "value": "Expert Therapists", "input_type": "text"},
    {"key": "home_stat_treatments_value", "group": "Home Statistics", "label": "Treatments number", "value": "35", "input_type": "number", "help_text": "A plus sign is displayed automatically."},
    {"key": "home_stat_treatments_label", "group": "Home Statistics", "label": "Treatments label", "value": "Treatments Offered", "input_type": "text"},
    {"key": "home_stat_years_value", "group": "Home Statistics", "label": "Years of experience number", "value": "3", "input_type": "number", "help_text": "A plus sign is displayed automatically."},
    {"key": "home_stat_years_label", "group": "Home Statistics", "label": "Years of experience label", "value": "Years Experience", "input_type": "text"},
    {"key": "home_years_badge_label", "group": "Home Statistics", "label": "Image badge label", "value": "Years of Excellence", "input_type": "text", "help_text": "Shown on the purple badge over the About image."},

    # About page
    {"key": "about_hero_label", "group": "About Page", "label": "Hero label", "value": "Our Story", "input_type": "text"},
    {"key": "about_hero_title", "group": "About Page", "label": "Hero title", "value": "About MEDPOINT", "input_type": "text"},
    {"key": "about_hero_description", "group": "About Page", "label": "Hero description", "value": "A sanctuary where wellness, beauty, and genuine care come together.", "input_type": "textarea"},
    {"key": "about_story_label", "group": "About Page", "label": "Story section label", "value": "Our Journey", "input_type": "text"},
    {"key": "about_story_title", "group": "About Page", "label": "Story section title", "value": "Where Wellness Meets Excellence", "input_type": "text"},
    {"key": "about_story_1", "group": "About Page", "label": "Story paragraph 1", "value": "Founded with a passion for holistic wellness, MEDPOINT Massage & Spa has grown into one of the most trusted names in premium spa services. Our journey began with a simple vision: to create a sanctuary where every guest feels renewed, refreshed, and rejuvenated.", "input_type": "textarea"},
    {"key": "about_story_2", "group": "About Page", "label": "Story paragraph 2", "value": "Today, we continue to uphold the highest standards of service, using only premium products and employing licensed, experienced therapists who are dedicated to your well-being. Every visit to MEDPOINT is a transformative experience that nurtures both body and soul.", "input_type": "textarea"},
    {"key": "about_values_label", "group": "About Page", "label": "Values section label", "value": "Why Choose Us", "input_type": "text"},
    {"key": "about_values_title", "group": "About Page", "label": "Values section title", "value": "Our Core Values", "input_type": "text"},
    {"key": "about_values_description", "group": "About Page", "label": "Values section description", "value": "What sets us apart in delivering exceptional wellness experiences.", "input_type": "textarea"},
    {"key": "about_passion_text", "group": "About Page", "label": "Passion description", "value": "We are passionate about helping you achieve holistic wellness and inner peace.", "input_type": "textarea"},
    {"key": "about_excellence_text", "group": "About Page", "label": "Excellence description", "value": "Every treatment is delivered with the highest standards of quality and care.", "input_type": "textarea"},
    {"key": "about_trust_text", "group": "About Page", "label": "Trust description", "value": "Your safety and comfort are our top priorities in everything we do.", "input_type": "textarea"},
    {"key": "about_care_text", "group": "About Page", "label": "Care description", "value": "Every guest is treated with genuine warmth and personalized attention.", "input_type": "textarea"},
    {"key": "about_team_title", "group": "About Page", "label": "Team section title", "value": "Meet Our Team", "input_type": "text"},
    {"key": "about_team_description", "group": "About Page", "label": "Team section description", "value": "Our experienced and licensed professionals bring years of expertise and genuine care to every session.", "input_type": "textarea"},
    {"key": "about_cta_title", "group": "About Page", "label": "Call-to-action title", "value": "Experience the MEDPOINT Difference", "input_type": "text"},
    {"key": "about_cta_description", "group": "About Page", "label": "Call-to-action description", "value": "Book your session today and discover why thousands trust us with their wellness journey.", "input_type": "textarea"},

    # Services, contact, and booking pages
    {"key": "services_hero_label", "group": "Services Page", "label": "Hero label", "value": "What We Offer", "input_type": "text"},
    {"key": "services_hero_title", "group": "Services Page", "label": "Hero title", "value": "Our Services", "input_type": "text"},
    {"key": "services_hero_description", "group": "Services Page", "label": "Hero description", "value": "Discover treatments thoughtfully designed to relax your body, restore your energy, and renew your spirit.", "input_type": "textarea"},
    {"key": "contact_hero_label", "group": "Contact Page", "label": "Hero label", "value": "Get In Touch", "input_type": "text"},
    {"key": "contact_hero_title", "group": "Contact Page", "label": "Hero title", "value": "Contact Us", "input_type": "text"},
    {"key": "contact_hero_description", "group": "Contact Page", "label": "Hero description", "value": "We would love to hear from you. Reach out with questions, feedback, or booking concerns.", "input_type": "textarea"},
    {"key": "contact_form_title", "group": "Contact Page", "label": "Contact form title", "value": "Send Us a Message", "input_type": "text"},
    {"key": "contact_form_description", "group": "Contact Page", "label": "Contact form description", "value": "We'll get back to you within 24 hours.", "input_type": "textarea"},
    {"key": "booking_hero_label", "group": "Booking Page", "label": "Hero label", "value": "Reserve Your Session", "input_type": "text"},
    {"key": "booking_hero_title", "group": "Booking Page", "label": "Hero title", "value": "Book Your Appointment", "input_type": "text"},
    {"key": "booking_hero_description", "group": "Booking Page", "label": "Hero description", "value": "Choose your preferred service, therapist, date, and time. We'll confirm your booking shortly.", "input_type": "textarea"},
    {"key": "booking_help_title", "group": "Booking Page", "label": "Help section title", "value": "Need Help?", "input_type": "text"},
    {"key": "booking_help_description", "group": "Booking Page", "label": "Help section description", "value": "Have questions about our services or need help picking the right treatment? Contact us!", "input_type": "textarea"},
    {"key": "booking_policy_title", "group": "Booking Page", "label": "Booking policy heading", "value": "Booking Policy", "input_type": "text"},
]

SITE_CONTENT_DEFAULTS = {item["key"]: item["value"] for item in SITE_CONTENT_FIELDS}
