# Generated by Django 4.2.29 on 2026-05-27 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_service_category'),
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_booking', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('booking_status', 'Booking Status Changed'), ('new_message', 'New Contact Message'), ('schedule_update', 'Schedule Updated'), ('system', 'System Notification')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_role', models.CharField(choices=[('admin', 'Admin Only'), ('staff', 'Staff Only'), ('all', 'Everyone')], default='all', max_length=10)),
                ('link', models.CharField(blank=True, help_text='Optional URL to link to when clicked', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to='website.therapist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
